### ISSUE TITLE
Error while setting up platform sensibosettingsonly

### ISSUE THREAD

**Issue by topexnative** [Amir974/home-assistant-custom-components#2]
Hi, getting this error when setting up the sensibo custom component.  I had the climate.sensibo state come up a while back, but now i'm not getting any state returned?  The error i'm getting is as below.

I'm running hass.io 0.88.1

`2019-02-24 23:10:00 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform sensibosettingsonly
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensibosettingsonly/climate.py", line 88, in setup_platform
    None, 99, None, "auto", None, my_target_temp_high, my_target_temp_low, my_api_key, my_min_temp, my_max_temp)
  File "/config/custom_components/sensibosettingsonly/climate.py", line 131, in __init__
    self.update()
  File "/config/custom_components/sensibosettingsonly/climate.py", line 138, in update
    uid = devices[self._name]`

**Comment by Amir974** [comment]
Seems like the issue is with a missing / no good "name" parameter - how do you have it setup ?

Should be something like this more or less (this is a sample setting from over 2 years ago!)

  - platform: sensibosettingsonly
    name: "Home"
    apiKey: !secret sensibo_api
    target_temp_low: 24
    target_temp_high: 26
    max_temp: 30
    min_temp: 16
    humidity: 45


to be honest...
I have not used this component since they launched the native Sensibo component - I recommend you look into it as a superior alternative!

**Comment by topexnative** [comment]
> Seems like the issue is with a missing / no good "name" parameter - how do you have it setup ?
> 
> Should be something like this more or less (this is a sample setting from over 2 years ago!)
> 
> * platform: sensibosettingsonly
>   name: "Home"
>   apiKey: !secret sensibo_api
>   target_temp_low: 24
>   target_temp_high: 26
>   max_temp: 30
>   min_temp: 16
>   humidity: 45
> 
> to be honest...
> I have not used this component since they launched the native Sensibo component - I recommend you look into it as a superior alternative!

Okay thanks, i will do.  However there is not much documentation or use cases around the native component?  Can you steer me to any GH repos that might have a good setup?  Yours?

**Comment by Amir974** [comment]
The samples in the documentation are really all you need as far as I know

https://www.home-assistant.io/components/climate.sensibo/


What are you missing beyond that?

**Comment by topexnative** [comment]
Thanks @Amir974 - i've now got the new Sensibo component working perfectly in the LL thermostat card.  Now for some automation!

**Comment by topexnative** [comment]
![image](https://user-images.githubusercontent.com/7575174/53319778-6b243e80-3938-11e9-934d-6f759bb19cfd.png)
