### ISSUE TITLE
Contains extra keys

### ISSUE THREAD

**Issue by Albertjvanr** [Amir974/home-assistant-custom-components#3]
Just a heads up, since HA version 0.88 I keep getting this error: 
"Your configuration contains extra keys that the platform does not support (but were silently accepted before 0.88). Please find and remove the following.This will become a breaking change.

- [name]. (See /config/configuration.yaml, line 66)."

The issue is that if I do remove [name], then I don't have a notify.pushoverglances service anymore so I cannot call the service.

**Comment by Amir974** [comment]
I’m sorry to hear you are having issues with this custom component
However I am not using / supporting these components since HA since added superior native solutions that I would recommend you try out...
